package org.tripsphere.poi.service;

import java.util.List;
import java.util.Optional;
import org.tripsphere.common.v1.GeoPoint;
import org.tripsphere.poi.v1.Poi;
import org.tripsphere.poi.v1.PoiFilter;

public interface PoiService {

    /**
     * Find a POI by its ID.
     *
     * @param id the POI ID
     * @return the POI if found
     */
    Optional<Poi> findById(String id);

    /**
     * Find a POI by its Amap ID.
     *
     * @param amapId the Amap ID
     * @return the POI if found
     */
    Optional<Poi> findByAmapId(String amapId);

    /**
     * Find all POIs by their IDs.
     *
     * @param ids the list of POI IDs
     * @return list of POIs found
     */
    List<Poi> findAllByIds(List<String> ids);

    /**
     * Search for POIs near a given location.
     *
     * @param location the center point in GCJ-02 coordinate system
     * @param radiusMeters the search radius in meters
     * @param limit the maximum number of results
     * @param filter optional search filter (can be null)
     * @return list of nearby POIs
     */
    List<Poi> searchNearby(GeoPoint location, double radiusMeters, int limit, PoiFilter filter);

    /**
     * Search for POIs within a bounding box.
     *
     * @param southWest the south-west corner in GCJ02 coordinate system
     * @param northEast the north-east corner in GCJ02 coordinate system
     * @param limit the maximum number of results
     * @param filter optional search filter (can be null)
     * @return list of POIs within the bounds
     */
    List<Poi> searchInBounds(GeoPoint southWest, GeoPoint northEast, int limit, PoiFilter filter);

    /**
     * Create a new POI.
     *
     * @param poi the POI to create (ID will be generated by the server)
     * @return the created POI with generated ID
     */
    Poi createPoi(Poi poi);

    /**
     * Batch create POIs.
     *
     * @param pois the list of POIs to create
     * @return the list of created POIs with generated IDs
     */
    List<Poi> batchCreatePois(List<Poi> pois);
}
