package org.tripsphere.poi.service;

import java.util.List;
import java.util.Optional;
import org.springframework.data.geo.Point;
import org.tripsphere.poi.model.PoiDoc;
import org.tripsphere.poi.model.PoiSearchFilter;

public interface PoiService {

    /**
     * Find a POI by its ID.
     *
     * @param id the POI ID
     * @return the POI if found
     */
    Optional<PoiDoc> findById(String id);

    /**
     * Find a POI by its Amap ID.
     *
     * @param amapId the Amap ID
     * @return the POI if found
     */
    Optional<PoiDoc> findByAmapId(String amapId);

    /**
     * Find all POIs by their IDs.
     *
     * @param ids the list of POI IDs
     * @return list of POIs found
     */
    List<PoiDoc> findAllByIds(List<String> ids);

    /**
     * Search for POIs near a given location.
     *
     * @param location the center point (longitude, latitude in WGS84)
     * @param radiusMeters the search radius in meters
     * @param limit the maximum number of results
     * @param filter optional search filter
     * @return list of nearby POIs
     */
    List<PoiDoc> searchNearby(
            Point location, double radiusMeters, int limit, PoiSearchFilter filter);

    /**
     * Search for POIs within a bounding box.
     *
     * @param southWest the south-west corner of the box
     * @param northEast the north-east corner of the box
     * @param limit the maximum number of results
     * @param filter optional search filter
     * @return list of POIs within the bounds
     */
    List<PoiDoc> searchInBounds(
            Point southWest, Point northEast, int limit, PoiSearchFilter filter);

    /**
     * Create a new POI.
     *
     * @param poiDoc the POI to create (ID will be generated by the server)
     * @return the created POI with generated ID
     */
    PoiDoc createPoi(PoiDoc poiDoc);

    /**
     * Batch create POIs.
     *
     * @param poiDocs the list of POIs to create
     * @return the list of created POIs with generated IDs
     */
    List<PoiDoc> batchCreatePois(List<PoiDoc> poiDocs);

    /**
     * Update an existing POI.
     *
     * @param id the ID of the POI to update
     * @param poiDoc the updated POI data
     * @return the updated POI if found
     */
    Optional<PoiDoc> updatePoi(String id, PoiDoc poiDoc);

    /**
     * Delete a POI by its ID.
     *
     * @param id the POI ID
     * @return true if deleted, false if not found
     */
    boolean deletePoi(String id);
}
