spring:
  application:
    name: trip-poi-service
  cloud:
    nacos:
      server-addr: localhost:8848
  data:
    mongodb:
      uri: mongodb://root:fudanse@localhost:27017
      database: poi_db

server:
  port: 24218

grpc:
  server:
    port: 50058
    enable-reflection: true

logging:
  level:
    org.tripsphere.poi: DEBUG
    net.devh.boot.grpc: INFO